### PR TITLE
Providing version information using the /version URL path

### PR DESCRIPTION
**Pull request by gtorodelvalle**
- 100% tests passed
- Implements https://github.com/telefonicaid/IoT-STH/issues/16
- Assigned to @frbattid

### CODE REVIEW

**Comment by iariasleon** [comment]
Also is useful append a line in log with the version and hash when start the app

**Comment by gtorodelvalle** [comment]
On it... ;) Thanks!

**Comment by gtorodelvalle** [comment]
As discussed internally with @frbattid and @iariasleon , the version information returned for the /version path is:
```
{
  version: 0.1.0-SNAPTHOT
}
```
On the other hand, the logs when the STH components starts up is the following:
```
time=2015-05-12T13:17:22.716Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_START | msg=Starting up STH server version 0.1.0-SNAPSHOT
time=2015-05-12T13:17:22.720Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_START | msg=Data model set to collection-per-entity
time=2015-05-12T13:17:22.894Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_DB_CONN_OPEN | msg=Connection to MongoDB mongodb://@localhost:27017/orion successfully established
time=2015-05-12T13:17:22.938Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_START | msg=Server started at http://localhost:8666
```

**Comment by frbattid** [comment]
LGTM, but a rebase is needed!

**Pull request merged**
