### PR TITLE
Updating README files to be compatible with MkDocs document site generator

### PR DESCRIPTION
**Pull request by ficoreulpgc**
In this commit we have updated the README files in order to be compatible with the parsing of MkDocs site generator tool. In summary, the changes are:

* Format of custom links in titles from **`## <a id="section1"></a> Introduction`** style to  **`## Introduction <a id="section1"></a>`**.
* Code blocks changed to fenced blocks. The style changes from **`<pre> make test </pre>`** to using triple inverted accents before and after the code.
* Escaped characters in URLs inside code blocks are now coded without escaping ( **&lt** is coded as **<**). 
* Link strings are now enclosed in **<>**. For example, **`www.google.com`** is now coded as **`<www.google.com>`** to receive proper link formatting.
* Links to the repository files apart from README files are now coded with absolute path.
* Some broken links to different repositories (like cygnus one) have been updated as they were broken.

All the changes but the alst two are needed because MkDocs uses Python-Markdown to parse and compile into HTML. This library seems to be more strict about format than GitHub renderer.

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
Hi @ficoreulpgc ! First off, thank you very much for your contribution... ;) Anyhow, I have some comments about it:
  - Please, send your pull request to the `develop` branch as mentioned in https://github.com/telefonicaid/IoT-STH/tree/release/0.1.0#section9 (point 9)
  - Your updates broke the numbering of the numbered lists, have a look at https://github.com/ficoreulpgc/IoT-STH/blob/master/README.md#section3 (all 1s :) ) and https://github.com/ficoreulpgc/IoT-STH/blob/master/README.md#section9 , for example.
As I said, thank you very much for your contributions. We would highly appreciate if you could fix the previous issues so we can land it into the `develop` branch so it can be included in the next release of the component.

**Comment by ficoreulpgc** [comment]
Hello back @gtorodelvalle!

We apologise for the inconvenience of our mistakes, they should be already corrected. 

We made a new pull request with the proper format as you have pointed to us and we hope is all fine now. We also duplicated the informative comment so this request can safely be discarded without losing any context of the change. The new pull request can be found here: https://github.com/telefonicaid/IoT-STH/pull/144.

Thank you for your time!

**Comment by gtorodelvalle** [comment]
Awesome!!! I am closing this PR now to avoid it landing into master... :) Thank you very much! See you in https://github.com/telefonicaid/IoT-STH/pull/144 :)

**Comment by gtorodelvalle** [comment]
Hi @ficoreulpgc ! First off and once again, thank you very much for your time and your contributions... ;) It looks awesome to me now :) The only thing pending would be to rebase the pull request with the latest contributions made to the `develop` branch... ;) Sorry, I could not review this pull request earlier... :(

**Pull request closed without merging**
